
PROGRAM=ptotheta

SOURCE=../f90trj/interpol.f90 ../f90trj/ptotheta.f90 tests.f90 tests_ptotheta.f90  

F95=gfortran

FFLAGS=-fdefault-real-8 -fbounds-check

LIBS=-L/lib -L/usr/lib -L../Lib -lnetcdff
INCLUDES = -I/usr/include -I ./

all : $(SOURCE)
	$(F95) $(FFLAGS) $(INCLUDES) $(SOURCE) -o $(PROGRAM) $(LIBS)
